url: https://playfulexperiences.github.io
baseurl: /2018DegreeShowWeb

# Site settings
title: Playful Experiences
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Jade Hall-Smith
  pic: "jade"
  social:
    - title: twitter
      url: https://twitter.com/VariegatedGames
    - title: linkedin
      url: https://www.linkedin.com/in/jade-hall-smith
    - title: globe
      url: https://variegated-games.com
  bio: >
    Part coder, part artist, all nerdy designer, Jade enjoys making games about mental
    health and disabilities. Her games focus on inclusivity and diversity as a means of
    inspiring players to empathise with others.

- name: Matthew Deline
  pic: "matt"
  social:
    - title: twitter
      url: https://twitter.com/mattdeline
    - title: github
      url: https://github.com/aradicaldreamer
    - title: youtube
      url: https://youtube.com/matthewdeline
    - title: linkedin
      url: https://linkedin.com/in/matthewdeline
    - title: globe
      url: https://www.matthewdeline.com
  bio: >
    Matt does his best thinking while on the road. When he’s not traveling, hiking, or
    sitting upside down in a roller coaster, he makes experimental board, arcade,
    narrative, and spatial games that encourage personal growth through interaction and play.

- name: Alex Fletcher
  pic: "alex"
  social: []
  bio: >
    Alex is an experienced Audio Engineer, who happens to play the trumpet. Not to toot his
    own horn, but he has now turned these skills to making games as well!

- name: Ben Tandy
  pic: "ben"
  social:
    - title: twitter
      url: https://twitter.com/frndcldben
    - title: globe
      url: https://www.afriendcalledben.com
  bio: >
    Ben is an interactive developer who started his career building interactive experiences for museums, galleries and expos. He transitioned over to game design and now seeks to create games that can help to present ideas and information in a captivating manner.<br /><br />

    His main passion is loud, over-stimulating arcade experiences that expect way too much from the player.


- name: Billy Karnchanapee
  pic: "billy"
  social:
    - title: twitter
      url: https://twitter.com/foxcircles
    - title: globe
      url: https://mitunayon.github.io/
  bio: >
    Game Developer who wants to inspire kindness by developing experiences with integrity and
    heart.<br/><br/>

    Billy is a game developer who makes games with the power of HEART! The shop was all out of the
    power of water.


- name: Doruk Hasdogan
  pic: "doruk"
  social:
    - title: twitter
      url: https://twitter.com/DorukHasdogan
    - title: behance
      url: https://www.behance.net/Malebolge
    - title: linkedin
      url: https://www.linkedin.com/in/dhasd
    - title: youtube
      url: https://www.youtube.com/channel/UCfGO0ZESaALif0Y12DF21kQ
  bio: >
    Indie game artist, game designer, environment designer from Turkey. Strong believer
    in power of strong/smart ideas, and concepts. Really interested in smart level and
    environment design.<br/><br/>

    A Turkish game artist, environment designer, and game developer, Doruk is committed
    to turning bold ideas into even bolder work in the games space, with a particular
    focus on level design.


- name: Ece Seyrek Hasdoğan
  pic: "ece"
  social:
    - title: twitter
      url: https://twitter.com/EceSeyrek
    - title: linkedin
      url: https://www.linkedin.com/in/ecesey
    - title: youtube
      url: https://www.youtube.com/channel/UCNsUSUUsKNzML6Vn3TCT4yw
    - title: instagram
      url: https://www.instagram.com/scarce.queen
    - title: behance
      url: https://www.behance.net/ScarceQueen
    - title: globe
      url: https://artstation.com/eceseyrekhasdogan
  bio: >
    Game artist, art director, concept artist, graphic designer from Turkey. Interested
    in VR, UI design, concept art, character face expressions and body gestures, environment
    design, logo design, color psychology.<br/><br/>

    Ece hails from Turkey, and works as a graphic designer and artist for games.
    From UI and logos to concept art and beautifully sculpted faces, Ece’s strong
    use of color shines everywhere!


- name: Julia Makivic
  pic: "placeholder"
  social:
    - title: twitter
      url: https://twitter.com/jmakivic

- name: Phoenix Perry
  pic: "phoenix"
  social:
    - title: twitter
      url: https://twitter.com/phoenixperry
    - title: globe
      url: http://www.phoenixperry.com
  bio: >
    Phoenix Perry creates physical games and user experiences. As an advocate for women
    in game development, she founded Code Liberation Foundation. In her role at
    Goldsmiths, University of London, she lecturers on Physical Computing and games and
    leads an MA in Independent Games and Experience Design.

- name: Raymond Vermeulen
  pic: "raymond"
  social:
    - title: twitter
      url: https://twitter.com/raymondvrmln
    - title: globe
      url: http://rvermeulen.com
  bio: >
    Raymond is a games writer and narrative designer currently living in the UK. He holds
    graduate degrees in writing and game design, following a major in philosophy of
    science. His work has been prominently featured on both his fridge and his corkboard.

- name: Tommy Graven
  pic: "tommy"
  social:
    - title: globe
      url: https://www.tommygraven.com
    - title: twitter
      url: https://twitter.com/tommy_goodgame
  bio: >
    Tommy is a 22 year old game developer working in C# and Unity and passionate about mobile games.

- name: Hugh Kennedy
  pic: "hughsk"
  social:
    - title: twitter
      url: https://twitter.com/hughskennedy
    - title: globe
      url: https://hughsk.io/
    - title: github
      url: https://github.com/hughsk
  bio: >
    Hugh is a roaming creative developer originally from Sydney, Australia. He's been making websites,
    interactive experiences and realtime visualisations since 2010, and has spent this year looking at games
    for activism and social change.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
